language: go

go:
  - "1.12"

addons:
  sonarcloud:
    organization: "dplabs"

git:
  depth: 1

install: true

script:
  - git fetch --unshallow --quiet
  - make test
  - sonar-scanner

deploy:
  provider: releases
  api_key: $TRAVIS_CI_TOKEN
  file: "cbox"
  skip_cleanup: true
  on:
    tags: true
