language: go

go:
  - "1.11"

addons:
  sonarcloud:
    organization: "dplabs"

git:
  depth: 1

install: true

script:
  - git fetch --unshallow --quiet
  - env GO111MODULE=on make test
  - sonar-scanner
